$ErrorActionPreference = "Stop"

$directories = @(
    "src/app/(public)/qui-sommes-nous",
    "src/app/(public)/rejoindre/succes",
    "src/app/(public)/blog/[slug]",
    "src/app/(public)/evenements/[id]",
    "src/app/(public)/formations/[id]",
    "src/app/(public)/webinaires",
    "src/app/(public)/bibliotheque",
    "src/app/(public)/annuaire",
    "src/app/(public)/agrobusiness/incubation",
    "src/app/(public)/agrobusiness/agripreneurs",
    "src/app/(public)/partenaires",
    "src/app/(public)/nous-soutenir",
    "src/app/(auth)/login",
    "src/app/(auth)/inscription",
    "src/app/(auth)/reset-password",
    "src/app/(auth)/callback",
    "src/app/(membres)/dashboard",
    "src/app/(membres)/profil/modifier",
    "src/app/(membres)/cotisation",
    "src/app/(membres)/messages",
    "src/app/(membres)/notifications",
    "src/app/(membres)/bibliotheque/[id]",
    "src/app/(membres)/bibliotheque/deposer",
    "src/app/(membres)/formations/[id]",
    "src/app/(membres)/formations/mes-certificats",
    "src/app/(membres)/webinaires/[id]",
    "src/app/(membres)/evenements",
    "src/app/(membres)/annuaire/[id]",
    "src/app/(membres)/opportunites",
    "src/app/(membres)/forum/[id]",
    "src/app/(membres)/forum/nouveau",
    "src/app/(membres)/services/demande",
    "src/app/(admin)/dashboard",
    "src/app/(admin)/membres/[id]",
    "src/app/(admin)/contenus/articles",
    "src/app/(admin)/contenus/documents",
    "src/app/(admin)/contenus/formations",
    "src/app/(admin)/contenus/evenements",
    "src/app/(admin)/paiements",
    "src/app/(admin)/analytics",
    "src/components/ui",
    "src/components/layout",
    "src/components/auth",
    "src/components/modules",
    "src/components/shared",
    "src/lib/supabase",
    "src/lib/utils",
    "src/lib/i18n",
    "src/messages",
    "src/types"
)

foreach ($dir in $directories) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }
}

$files = @(
    "src/app/(public)/page.tsx",
    "src/app/(public)/qui-sommes-nous/page.tsx",
    "src/app/(public)/rejoindre/page.tsx",
    "src/app/(public)/rejoindre/succes/page.tsx",
    "src/app/(public)/blog/page.tsx",
    "src/app/(public)/blog/[slug]/page.tsx",
    "src/app/(public)/evenements/page.tsx",
    "src/app/(public)/evenements/[id]/page.tsx",
    "src/app/(public)/formations/page.tsx",
    "src/app/(public)/formations/[id]/page.tsx",
    "src/app/(public)/webinaires/page.tsx",
    "src/app/(public)/bibliotheque/page.tsx",
    "src/app/(public)/annuaire/page.tsx",
    "src/app/(public)/agrobusiness/page.tsx",
    "src/app/(public)/agrobusiness/incubation/page.tsx",
    "src/app/(public)/agrobusiness/agripreneurs/page.tsx",
    "src/app/(public)/partenaires/page.tsx",
    "src/app/(public)/nous-soutenir/page.tsx",
    "src/app/(auth)/login/page.tsx",
    "src/app/(auth)/inscription/page.tsx",
    "src/app/(auth)/reset-password/page.tsx",
    "src/app/(auth)/callback/page.tsx",
    "src/app/(membres)/layout.tsx",
    "src/app/(membres)/dashboard/page.tsx",
    "src/app/(membres)/profil/page.tsx",
    "src/app/(membres)/profil/modifier/page.tsx",
    "src/app/(membres)/cotisation/page.tsx",
    "src/app/(membres)/messages/page.tsx",
    "src/app/(membres)/notifications/page.tsx",
    "src/app/(membres)/bibliotheque/page.tsx",
    "src/app/(membres)/bibliotheque/[id]/page.tsx",
    "src/app/(membres)/bibliotheque/deposer/page.tsx",
    "src/app/(membres)/formations/page.tsx",
    "src/app/(membres)/formations/[id]/page.tsx",
    "src/app/(membres)/formations/mes-certificats/page.tsx",
    "src/app/(membres)/webinaires/page.tsx",
    "src/app/(membres)/webinaires/[id]/page.tsx",
    "src/app/(membres)/evenements/page.tsx",
    "src/app/(membres)/annuaire/page.tsx",
    "src/app/(membres)/annuaire/[id]/page.tsx",
    "src/app/(membres)/opportunites/page.tsx",
    "src/app/(membres)/forum/page.tsx",
    "src/app/(membres)/forum/[id]/page.tsx",
    "src/app/(membres)/forum/nouveau/page.tsx",
    "src/app/(membres)/services/demande/page.tsx",
    "src/app/(admin)/layout.tsx",
    "src/app/(admin)/dashboard/page.tsx",
    "src/app/(admin)/membres/page.tsx",
    "src/app/(admin)/membres/[id]/page.tsx",
    "src/app/(admin)/contenus/articles/page.tsx",
    "src/app/(admin)/contenus/documents/page.tsx",
    "src/app/(admin)/contenus/formations/page.tsx",
    "src/app/(admin)/contenus/evenements/page.tsx",
    "src/app/(admin)/paiements/page.tsx",
    "src/app/(admin)/analytics/page.tsx",
    "src/lib/supabase/client.ts",
    "src/lib/supabase/server.ts",
    "src/lib/utils/formatters.ts",
    "src/lib/utils/validators.ts",
    "src/lib/i18n/routing.ts",
    "src/lib/i18n/request.ts",
    "src/messages/fr.json",
    "src/middleware.ts",
    "src/types/database.ts",
    "src/types/index.ts"
)

foreach ($file in $files) {
    if (-not (Test-Path $file)) {
        New-Item -ItemType File -Force -Path $file | Out-Null
    }
}
